### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by jonstorer** [greghaskins/spectrum#10]
Greg,

I realize I should know this. But I'm new to JAVA. I'm coming from Ruby & Node which has build tools that I understand very well. However, I don't know gradle or maven or ant at all. 

Would it be possible to have some installation instructions included in the readme? I looked for this package on maven, but alas.

Any help would be appreciated!

**Comment by jonstorer** [comment]
So follow up. I just found the Jar. Is there anyway (that you know of) to use maven to point to this jar on github? Well any "built in" method for this. I'm pretty sure I could hack something together, but I'd prefer not to.

Thanks, Jon

**Comment by greghaskins** [comment]
That's an excellent request. Adding Spectrum to Maven Central and/or JCenter has been on my backlog for a while (see #8). That would make it as easy as declaring a dependency in your `pom.xml` or `gradle.build` or whatever. Or even, just having that central place to download the jar.

I'll see if I get some time to sort that out in the next couple days; having external parties interested in the project provides some extra motivation.

**Comment by greghaskins** [comment]
@jonstorer I have updated the readme with [instructions for getting started](https://github.com/greghaskins/spectrum#getting-started) with either Maven or Gradle. Let me know if that helps clarify things.

The binaries are still published to my personal account on Bintray, but I'll have them in JCenter and Maven Central eventually (meaning less configuration required).
