### ISSUE TITLE
Docs: Generating Test Reports

### ISSUE THREAD

**Issue by JohannesRudolph** [greghaskins/spectrum#113]
The docs are missing a section on the recommended way to generate test reports. We are in the process of starting to use spectrum more seriously but were wondering what's the recommended way to get properly formatted test reports/progress when running spectrum from the CLI.

**Comment by greghaskins** [comment]
Hi @JohannesRudolph, thanks for reaching out. Spectrum is built on top of JUnit4, so it uses whatever mechanism you have prefer for JUnit. However you would run and generate reports for JUnit4 will "just work" with Spectrum tests right alongside your traditional JUnit4 tests, both IDE and CLI.

I use the built-in [JUnit support from Gradle](https://docs.gradle.org/current/userguide/java_plugin.html#sec:java_test), which both prints failing tests to the console and creates report files (HTML and/or XML). The [Maven Surefire plugin](http://maven.apache.org/surefire/maven-surefire-plugin/) has similar configuration, if that's your preferred build tool.

If you one of these (or another option) works really well and you think it would be helpful to have a couple of links or notes in the Spectrum docs, feel free to submit a PR.
