### ISSUE TITLE
Variables+awaitility only work if used in the same thread

### ISSUE THREAD

**Issue by mxk1235** [greghaskins/spectrum#115]
i am not sure what you can do on your end, but thought I would report it anyhow.   the following test case fails because Variables use a ThreadLocal, and awaitility by default happens to run in a separate one.  The only way it works is if the user does an 
`await().pollInsSameThread()`.

```
java.lang.AssertionError: 
Expected: not (null or an empty string)
     but: was null
Expected :not (null or an empty string)
     
Actual   :null
```

```
package test;

import com.greghaskins.spectrum.Spectrum;
import com.greghaskins.spectrum.Variable;
import org.junit.runner.RunWith;

import static com.greghaskins.spectrum.Spectrum.describe;
import static com.greghaskins.spectrum.Spectrum.it;
import static org.awaitility.Awaitility.await;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.isEmptyOrNullString;
import static org.hamcrest.Matchers.not;

@RunWith(Spectrum.class)
public class VariableTest {{
  describe("suite", () -> {
    final Variable<String> var = new Variable<>();
    it("test", () -> {
      var.set("value");
      await().until(() -> {
        assertThat(var.get(), not(isEmptyOrNullString()));
        return true;
      });
    });
  });
}}
```

**Comment by greghaskins** [comment]
Interesting scenario, thanks for reaching out @mxk1235. I don't think we've actually set a formal design direction on how Spectrum should work in a multi-threaded scenario.

I know @ashleyfrieze had some thoughts about running tests in parallel, which is partly why `Variable` is thread-local. The thinking there is that multiple tests in the same suite could run in parallel without stepping on each other.

By contrast, in the awaitility situation you're describing, it would be simpler if those variables were shared across threads. At minimum, it might be worth a documentation tweak so that the current behavior is more clear.

**Comment by ashleyfrieze** [comment]
The design aim from my side was to make tests thread safe so that they could be parallelised.

The idea that test state should be shared between tests is already problematic. Using Variable outside of 'it' is kind of asking for trouble. 

I'm not sure whether Spectrum should solve this or whether users should make their own equivalent of Variable for this case.

I should try not to point out that private instance variables of your test class are effectively references to shared test state.

**Comment by mxk1235** [comment]
I get the same result if I move the variable inside the `it`.

```
package com.memsql.cloud;

import com.greghaskins.spectrum.Spectrum;
import com.greghaskins.spectrum.Variable;
import org.junit.runner.RunWith;

import static com.greghaskins.spectrum.Spectrum.describe;
import static com.greghaskins.spectrum.Spectrum.it;
import static org.awaitility.Awaitility.await;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.isEmptyOrNullString;
import static org.hamcrest.Matchers.not;

/**
 * Created by mxk on 5/17/17.
 */
@RunWith(Spectrum.class)
public class VariableTest {{
  describe("suite", () -> {
    it("test", () -> {
      final Variable<String> var = new Variable<>();
      var.set("value");
      await().until(() -> {
        assertThat(var.get(), not(isEmptyOrNullString()));
        return true;
      });
    });
  });
}}
```

**Comment by ashleyfrieze** [comment]
Sorry. What I wrote was ambiguous. Try defining a private String member of your test class. That can be used across threads. 

Variable is currently only thread exclusive. I'm not sure it should be thread agnostic. You could make your own equivalent. It's very easy.

**Comment by mxk1235** [comment]
i agree, it is easy to make an agnostic reference.  just a bit surprising when you encounter it.

**Comment by ashleyfrieze** [comment]
I agree with Greg. We should document this limitation. It will become clearer why it is this way when we introduce parallel execution.

**Comment by greghaskins** [comment]
(Cleaning up some old issues, so I'm just coming back to this one now.)

I think the real behavior we want from `Variable` is not necessarily a _thread_ local, but a _spec_ local, one that is not shared across atomic tests, but is consistent within the execution scope of the current spec. Those specs themselves could reasonably use multiple threads, as we've seen in this example. 

I will noodle on this a bit, and perhaps submit a PR for review.

**Comment by ashleyfrieze** [comment]
When I get back onto the parallelisation piece, I'm going to depend on being able to run atomic tests in any order in any threads, which means that `Variable`  and `let` need to be thread safe. I was going to provide another mechanism for sharing things across threads.

Very embryonic stuff here - https://github.com/ashleyfrieze/spectrum/tree/ParallelExecution

**Comment by bjornblomqvist** [comment]
Just want add that i just hit the same issue. Wasted 30 minutes on it. That `Variable` uses thread local is very **unexpected**. I have used rspec quite a lot so i had expected `Variable` to behave the same as let in rspec.

I have multiple threads as I am verifying that a link i give to a REST API is actually called by setting up a temporary URL handler that sets the variable to true when called.

```
describe("/stats", () -> {)

    Variable<Boolean> hasFetchedUrl = new Variable();

    beforeAll(() -> {
        ...
    
        get("/temp_url_handler", (req, res) -> {
            hasFetchedUrl.set(true);
            return "";
        });
    
        ...
        
        Unirest.get("http://localhost:14567/stats")
          .queryString("url", "http://localhost:14567/temp_url_handler")
          .asString();
    });
    
    it("should fetch the given url", () -> {
        assertThat(hasFetchedUrl.get(), is(true));
    });
}
```

I solved this by creating my own Variable class.

**Comment by bjornblomqvist** [comment]
On the topic of parallelisation. Couldn't you just create multiple object trees with its own state by running the root describe block multiple times?

**Comment by bjornblomqvist** [comment]
Created a pull request with a note in the java doc saying that Variable class state is thread local. #117

**Comment by ashleyfrieze** [comment]
Thanks @bjornblomqvist 

@greghaskins - this is making me reconsider the wisdom of making it threadlocal by default. Shall I look at making a PR to reverse that? I will want something to be segregated by thread in the parallel version of `Spectrum`, but I can already guess that you're reading from @bjornblomqvist 's PR a huge motivation to make this non thread specific ;)

**Comment by greghaskins** [comment]
It is unexpected behavior, I'm sorry you got burned @bjornblomqvist !

Yes, @ashleyfrieze I think it probably makes sense to make `Variable` thread-agnostic at least by default. That way we can follow the principle of least surprise, and still keep our options open for parallization. 

I'm traveling this week with almost no connectivity; I should be able to review, merge, and push any changes on the weekend.

**Comment by bjornblomqvist** [comment]
Thanks for the quick response and also **big thanks** for creating a great library!

**Comment by ashleyfrieze** [comment]
@greghaskins - have a look at #118 when you have a moment.

**Comment by greghaskins** [comment]
Good deal. I'll close this issue once #118 merges.

**Comment by mxk1235** [comment]
thanks all
