### ISSUE TITLE
Include package in Maven Central

### ISSUE THREAD

**Issue by greghaskins** [greghaskins/spectrum#12]
To make it stupid-easy to integrate. Should be possible to sync from JCenter, See #8

**Comment by jonstorer** [comment]
👍

**Comment by kbhaskett** [comment]
👍

**Comment by Hefley** [comment]
👍

**Comment by julamula** [comment]
👍

**Comment by douglasrlee** [comment]
👍

**Comment by jaysonbucy** [comment]
👍

**Comment by noheltcj** [comment]
👍

**Comment by greghaskins** [comment]
Wow, lots of 👍 all on the same day! I'll start working through the process to put Spectrum on Maven Central. My goal is for `1.0.0` to be the first release there. There are only a [few outstanding issues](https://github.com/greghaskins/spectrum/milestone/1) left for that milestone.

**Comment by greghaskins** [comment]
I've got a JIRA issue with Sonatype opened to get access to the Central repo. It might take a couple business days to get approved. https://issues.sonatype.org/browse/OSSRH-25022

**Comment by greghaskins** [comment]
Will do a manual deploy to maven central for first version, the the build pipeline will automatically do it moving forward.

**Comment by wormangel** [comment]
Will this happen anytime soon?

**Comment by greghaskins** [comment]
Turns out I can't manually push `1.0.0` to maven central, since its `pom.xml` needs some tweaking. I could either 
- (1) wait until the `1.1.0` release, or 
- (2) branch off a `1.0.1` and publish that.

I think I'm going with Option 2, since it will still take a bit of work to firm up the `1.1.0` release. So, to answer @wormangel, hopefully in the next couple days if everything works as it's supposed to.

**Comment by wormangel** [comment]
Cool! Will keep watching. Great work btw!

**Comment by greghaskins** [comment]
I've got the artifacts pushed to OSSRH, now waiting on it to sync to Maven Central. I think they will respond to [this ticket](https://issues.sonatype.org/browse/OSSRH-25022) when the sync is activated.

**Comment by greghaskins** [comment]
Done. See [Release 1.0.2](https://github.com/greghaskins/spectrum/releases/tag/1.0.2).
