### ISSUE TITLE
Focused tests/contexts with `fit()` and `fdescribe()`

### ISSUE THREAD

**Issue by greghaskins** [greghaskins/spectrum#16]
Similar to Jasmine's API: http://jasmine.github.io/2.1/focused_specs.html

**Comment by greghaskins** [comment]
Not sure whether we want to settle on Jasmine style `fit()` or more like Mocha with `it.only()`

Should have some consistency with ignoring tests (#5, `xit()` vs `it.skip()` or something)

**Comment by kdroberson** [comment]
+1 !

**Comment by jonstorer** [comment]
+1! Any timeline on this? Or direction for a PR?

**Comment by greghaskins** [comment]
I've started on a first-pass implementation for `xit` / `xdescribe` that is related to the focused tests feature as well. I could ship one or the other in the next week or so. 

@jonstorer @kdroberson would focused tests or skipped tests be more useful in the near term? 

Moving forward, there are some structural changes that need to happen to make it easier for people other than me to contribute PRs. Some of the implementation is a little too clever for its own good, and the tests don't have a very consistent style/ format.

**Comment by jonstorer** [comment]
@greghaskins tbh, focusing would be better up front.

**Comment by greghaskins** [comment]
Agreed. Especially since there's no easy way to run just a single test (or subset of tests). I'll implement `fit()` and `fdescribe` first. Perhaps even just `fit()` to start with, in case the context-level logic gets tricky.

In terms of API, I've been essentially copying Jasmine as much as possible, mostly because it is simpler than Mocha and RSpec which each have numerous ways to accomplish the same thing. I am open to feedback/ideas, though.

**Comment by jonstorer** [comment]
Get a pull request started and I'll happily provide feedback. I agree with the Jasmine approach since simpler is always better.

I'm new to a team of Java developers, but I'm coming from the Ruby/JavaScript world. Between us we should be able to provide help. 

Thanks for keep us in the loop.

**Comment by greghaskins** [comment]
I've got PR #23 out there now for `fit` and `fdescribe`. If you're interested, I'd welcome any feedback you have. Otherwise I'll merge and push a `0.6.0` release by midweek.

**Comment by greghaskins** [comment]
Merged #23 and released [0.6.0](https://github.com/greghaskins/spectrum/releases/tag/0.6.0) with `fdescribe` and `fit`. It's available now on jcenter.
