### ISSUE TITLE
Exceptions in afterEach mask exceptions in beforeEach

### ISSUE THREAD

**Issue by pivotal-stuart-pollock** [greghaskins/spectrum#40]
For a given test (Spectrum.it), if both a beforeEach and its afterEach raises an exception, then the test fails and reports the afterEach's exception, thereby masking the beforeEach exception.

**Comment by greghaskins** [comment]
As per the discussion in #41, we'll use that PR as an interim fix, then push the [RSpec-style behavior](https://github.com/greghaskins/spectrum/pull/41#issuecomment-238729178) as a separate feature. I'll keep this issue open as a placeholder/reminder to make sure we get it sorted before `1.0.0`.

**Comment by greghaskins** [comment]
I've started working on a PR that will implement the proper behavior, in line with RSpec. It's just off on a branch at the moment: [rspec-style-error-handling](https://github.com/greghaskins/spectrum/tree/rspec-style-error-handling)
