### ISSUE TITLE
Paramaterized specs

### ISSUE THREAD

**Issue by ashleyfrieze** [greghaskins/spectrum#57]
As a follow up to the `scenarioOutline` idea, I'd like to make it simple and declarative to have parameterized tests in Spectrum.

Features:

- any type of spec/suite should be easily parameterized without writing boilerplate
- the explicit gherkin construct of `scenarioOutline` should be supported directly

**Comment by ashleyfrieze** [comment]
In #58, the syntax is

```java
allOf(Stream<T> .. , SpectrumFunction, Consumer<T> block)
```

Perhaps the name should be something more inspiring than all of - perhaps `withTemplate`?

**Comment by greghaskins** [comment]
Closing this issue, since we have #58 and #80 instead.
