### ISSUE TITLE
Support `context` keyword from Ginkgo?

### ISSUE THREAD

**Issue by ashleyfrieze** [greghaskins/spectrum#63]
http://onsi.github.io/ginkgo/ has level of abstraction between `describe` and `it` in the form of `context`. This would be easy enough to add in the same way that the `GherkinSyntax` was added. Worth doing?

**Comment by greghaskins** [comment]
I think this is a good idea, `context` as an alias for `describe`.  It makes tests read a little nicer when nesting suites. To be consistent, we should also have `xcontext` and `fcontext`.
