### ISSUE TITLE
Consolidation refactoring - before/around/let - the grand unified theory of hooks

### ISSUE THREAD

**Issue by ashleyfrieze** [greghaskins/spectrum#76]
There are several constructs within Spectrum which are essentially hooks that run before/after or both before and after execution blocks. The `let` supplier is refreshed on a test by test basis. The `beforeAll` is run around a set of items. The `beforeEach` runs before individual specs.

All of these could be consolidated into a hook plugin architecture. We keep the user interface and just modify the internals so that there's a chain of hooks at each level of the hierarchy. Those hooks may or may not be connected with Supplier references that the test definition has kept. The hooks may or may not run at the level of a suite or down at the individual "test". For this to work, the concept of `Atomic` already incubating on #56 will be useful.

The hooks will also be exposed with functions `hook` and `localHook` or similar, for ANY external plugin to be possible. This means the JUnit rules implementation of #56 can become relegated to a plugin.

Hopefully a lot of code will go away in `Suite` with this change, as there'll only really be one implementation of lots of things suite does as a chain.

**Comment by ashleyfrieze** [comment]
@greghaskins - this can now be closed, I think.

**Comment by greghaskins** [comment]
Closed by #77
