### ISSUE TITLE
features listed on README not released yet under tag v1.0.0

### ISSUE THREAD

**Issue by marioluan** [greghaskins/spectrum#84]
The latest released git tag is 1.0.0, but there're a lot of amazing features listed on README which are not under any tag.

Wouldn't that be better to remove those features from README until they are released or add notes telling the user those features are not under the latest released tag yet?

There are about ~ 100 commits on master branch since v1.0.0. When are you guys going to release a new tag with all those features included?

**Comment by marioluan** [comment]
cc @greghaskins @ashleyfrieze

**Comment by greghaskins** [comment]
Yep, that is a clear oversight on our part. What started as something we hoped to ship quickly has slipped further along, and the README has drifted pretty far from the latest release. I'm pushing an update to call that out clearly now.

As you noticed we've actually made quite a few changes. We are hoping to close the remaining PRs soon and address some cleanup items. We'll either then push a `1.x` with the new features (if we can keep things backward-compatible) or a `2.0` if not. In terms of timeline, my guess is probably weeks and not months. Part of the reason for the current disconnect is we don't have a handle on how many people are even using this tool, so folks such as yourself help keep us in check. I certainly appreciate that.

**Comment by marioluan** [comment]
That's really great news!

Let me know if you need help with anything.

Also, there is a project ([https://libraries.io/](https://libraries.io/)) which keeps track of libraries being used by open-source projects. Unfortunately, they only have support for java's maven.

But I think you should check that out, maybe it's a good start (perhaps migrate from jcenter to maven) to keep track of users from the library ;).

**Comment by greghaskins** [comment]
Good tip, thanks! Yep, maven central has been on the radar for a while, I just have to cut through the administrative cruft to make it happen (see #12).

An obvious and immediate need, of course, is to improve the docs and set up better tooling for keeping our releases in sync with those docs. If you're interested, hop on our chat at https://gitter.im/greghaskins/spectrum . We also appreciate any testing you might be able to provide for these latest round of features. Particularly, the Spring/Mockito/etc. compatibility we've been working on over in #56 . Everyone uses their tools in a slightly different way, so it's helpful to bring in others so we can cover as many bases as possible.

**Comment by ashleyfrieze** [comment]
> We also appreciate any testing you might be able to provide for these latest round of features.

:+1: 

@marioluan if you'd like to road test `master` or any of the pending PRs, then you could make an ad-hoc build from a clone of the project. Happy to help you with that if you need it. I'm never far from _gitter_. I'm in UTC time zone. Greg's in EST.
