### ISSUE TITLE
Tag tests to run a filtered subset

### ISSUE THREAD

**Issue by greghaskins** [greghaskins/spectrum#9]
RSpec has a [`--tag` command line option](https://www.relishapp.com/rspec/rspec-core/v/2-4/docs/command-line/tag-option) that can query or run only tests matching certain criteria (e.g. `speed:slow` or `integration:true`).

**Comment by ashleyfrieze** [comment]
Duplicates #53

**Comment by greghaskins** [comment]
Closed by #64
