### ISSUE TITLE
REQUEST: Include the variable class in the next release

### ISSUE THREAD

**Issue by tripleentendre** [greghaskins/spectrum#91]
This really a request but are you planning on including the variable class in your next release? We use spectrum in our java and android projects and I've run across lots of situations where it would come in handy. Thanks!

**Comment by greghaskins** [comment]
@tripleentendre thanks for the feedback! 

If you're referring to the `Variable<T>` wrapper class ([here's an example](https://github.com/greghaskins/spectrum/blob/master/src/test/java/specs/VariableSpecs.java)) then yep, we've definitely got that in there for `1.1.0`, along with quite a few more features.

I'm in the cleanup and release prep stages, so you should see it out on JCenter in the next week or so.
