### ISSUE TITLE
how to set expected exception

### ISSUE THREAD

**Issue by rlvillacarlos** [greghaskins/spectrum#92]
I would like to ask whether it is possible to define expected exceptions for it blocks. Currently I am using try catch to handle this. And I am wondering if this is possible with spectrum?

**Comment by greghaskins** [comment]
Assertions (including expected exceptions) aren't the purview of Spectrum itself, but there are a few options, depending on your preferences. 

One option is to use an assertion library like AssertJ which has [a nice way to verify exceptions](http://joel-costigliola.github.io/assertj/assertj-core-features-highlight.html#exception-assertion). Apparently `assertThrows` for lambdas is [slated for JUnit 4.13](https://github.com/junit-team/junit4/wiki/4.13-Release-Notes) if/when that is released. 

Another option is to write a helper function to hide some of the boilerplate. It could look like `it("should throw Blah", expected(BlahException.class, ()-> {/* ... */});`, or if you're ambitious, a Hamcrest matcher for something like: `assertThat(() -> foo.doSomething(123), doesThrow(SomeException.class));`.

Googleing around, [this StackOverflow](http://stackoverflow.com/a/24621006) answer has some interesting ideas too.

There will be some basic support for JUnit `@Rule`s like `ExpectedException` in the next release of Spectrum, but it would probably be cleaner (IMHO) to use one of the above.

**Comment by rlvillacarlos** [comment]
Thanks. I actually created a helper class that includes the boiler plate codes just for that. I was just worried that somehow that JUnit's `@ExpectedException` can be used in Spectrum and that I am just not aware how do it.
