### ISSUE TITLE
When describe block contains () I am getting <no name> in IntelliJ

### ISSUE THREAD

**Issue by zifnab87** [greghaskins/spectrum#97]
```
describe("after creation of attribute", () -> {
        describe( "latest()", () -> {
                it("should return 200", () -> {
                    mockMvc.perform(get("/api/latest/attribute")).andExpect(status().isOk());
                });
        });
});
```

if I replace `latest()` with `latest` everything works fine!

![image](https://cloud.githubusercontent.com/assets/526062/23470254/9022c088-feae-11e6-8e8f-aecc2d786cd0.png)

![image](https://cloud.githubusercontent.com/assets/526062/23470273/a57a4a0a-feae-11e6-9db8-376bddee3d77.png)

Thank you!

**Comment by greghaskins** [comment]
@zifnab87 I have a sense of what the bug is here, probably related to #3.

Which version of Spectrum are you using? The fix to #3 hasn't landed in a release yet, it will be included with `1.1.0`.

**Comment by zifnab87** [comment]
Hi @greghaskins! I am using 1.0.2 :) Thanks!

**Comment by ashleyfrieze** [comment]
`1.1.0` should fix this. Please try it.

**Comment by ashleyfrieze** [comment]
Please confirm that your issue is resolved @zifnab87

**Comment by ashleyfrieze** [comment]
@greghaskins - I'm pretty sure this is fixed, shall we close this issue?

**Comment by greghaskins** [comment]
JUnit4 does weird things with parentheses and string parsing of test names. `1.1.0` included a fix that at least makes this readable in IDEs (by replacing/cleaning weird characters in test names). Not ideal, but it works. JUnit5 will be much nicer in this regard.
